.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 1/14/13               \" DATE 
.Dt flynn 1               \" Program name and manual section number 
.Os Darwin
.Sh NAME                  \" Section Header - required - don't modify 
.Nm flynn
.\" Use .Nm macro to designate other names for the documented program.
.Nd A block differential animation encoder.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Op options
.Op Fl o Ar path
.Ar directory
.Nm
.Op options
.Op Fl o Ar path
.Ar file1
.Op Ar file2 ...
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Nm
evaluates a series of input animation frame images and encodes them into a sequence of output
images which represent the animation in a (generally) more efficient form. This encoded format,
called Block Differential Frame Encoding, is based on an implementation used by Apple on the
apple.com website.
.Pp
Each of the components of a BDFE animation (a JSON manifest file and a number of encoded image
files) can be directly decoded by a modern Web browser. As a result, BDFE animations can be
played on a wide variety of platforms, including mobile browsers such as Mobile Safari on iOS.
.Pp
BDFE animations can be very efficient for content of the sort to which it is well suited: short
animations and motion graphics in which a relatively small region of the image changes from frame
to frame. The format is not especially well suited to encoding video.
.Pp
.Nm
Underlining is accomplished with the .Ar macro like this:
.Ar underlined text .
.Pp                      \" Inserts a space
A list of items with descriptions:
.Bl -tag -width -indent  \" Begins a tagged list 
.It item a               \" Each item preceded by .It macro
Description of item a
.It item b
Description of item b
.El                      \" Ends the list
.Pp
The following options supported by
.Nm
for encoding:
.Bl -tag -width -indent  \" Differs from above in tag removed 
.It Fl n -name
The name of the animation. This name is used as the base name for output files (e.g., the name 'hello'
might produce files 'hello_manifest.json', 'hello_keyframe.png', 'hello_001.png', and so fourth).
.It Fl o -output Ar path
Output encoded animation files under
.Ar path.
.It Fl b
Description of -b flag
.El                      \" Ends the list
.Pp
.\" .Sh ENVIRONMENT      \" May not be needed
.\" .Bl -tag -width "ENV_VAR_1" -indent \" ENV_VAR_1 is width of the string ENV_VAR_1
.\" .It Ev ENV_VAR_1
.\" Description of ENV_VAR_1
.\" .It Ev ENV_VAR_2
.\" Description of ENV_VAR_2
.\" .El                      
.Sh FILES                \" File used or created by the topic of the man page
.Bl -tag -width "/Users/joeuser/Library/really_long_file_name" -compact
.It Pa /usr/share/file_name
FILE_1 description
.It Pa /Users/joeuser/Library/really_long_file_name
FILE_2 description
.El                      \" Ends the list
.\" .Sh DIAGNOSTICS       \" May not be needed
.\" .Bl -diag
.\" .It Diagnostic Tag
.\" Diagnostic informtion here.
.\" .It Diagnostic Tag
.\" Diagnostic informtion here.
.\" .El
.Sh SEE ALSO 
.\" List links in ascending order by section, alphabetically within a section.
.\" Please do not reference files that do not exist without filing a bug report
.Xr a 1 , 
.Xr b 1 ,
.Xr c 1 ,
.Xr a 2 ,
.Xr b 2 ,
.Xr a 3 ,
.Xr b 3 
.\" .Sh BUGS              \" Document known, unremedied bugs 
.\" .Sh HISTORY           \" Document history if command behaves in a unique manner