.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 1/14/13               \" DATE 
.Dt flynn 1               \" Program name and manual section number 
.Os Darwin
.Sh NAME                  \" Section Header - required - don't modify 
.Nm flynn
.\" Use .Nm macro to designate other names for the documented program.
.Nd A block differential animation encoder.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Op options
.Op Fl o Ar path
.Ar directory
.Nm
.Op options
.Op Fl o Ar path
.Ar file1
.Op Ar file2 ...
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Nm
evaluates a series of input animation frame images and encodes them into a sequence of output
images which represent the animation in a (generally) more efficient form. This encoded format,
called Block Differential Frame Encoding (or: a Flynn animation), is essentially a naive but
fast video codec. The Flynn animation format is based on an implementation used by Apple on the
apple.com website.
.Pp
Each of the components of a Flynn animation (a JSON manifest file and a number of encoded image
files) can be decoded directly by a modern Web browsers. As a result, Flynn animations can be
played on a wide variety of platforms, including mobile browsers such as Mobile Safari.
.Sh OPTIONS
The following options are supported by
.Nm
for encoding:
.Bl -tag -width -indent  \" Differs from above in tag removed 
.It Fl n -name Ar name
The name of the animation. This name is used as the base name for output files (e.g., the
.Ar name
\'hello' might produce files 'hello_manifest.json', 'hello_keyframe.png', 'hello_001.png',
and so fourth). The default name for animations is 'flynn'.
.It Fl o -output Ar path
Output encoded animation files under
.Ar path.
.It Fl b -block-size Ar size
Use the dimesion
.Ar size
as the block size for the animation. The
.Ar size
is used for both dimensions of a block, which must be square. You can use any block size you like
provided it is:
1) a factor of the encoded image size; and
2) both greater than 1 and less than the image size (
.Fl I -image-size
). The default block
.Ar size
is 8.
.It Fl t -block-threshold Ar count
Use the block error threshold
.Ar count
for determining differences between frames. The block error threshold refers to the number
of pixels in a single block which do not exactly match between two frames before the entire block
is updated. A threshold of 1 means a single pixel difference between frames causes that pixel's block
to be updated; a threshold of 10 means 10 pixels must differ before the block is updated. The default threshold
.Ar count
is 1.
.It Fl I -image-size Ar size
Use the dimension
.Ar size
as the image size for encoded block-stream images. The
.Ar size
is used for both dimensions of the image, which must be square. You can use any image size you like provided
that it is a multiple of the block size (
.Fl b -block-size
). The default image size is 1624, which is probably what you want.
.It Fl v -verbose
Display more information about the conversion process.
.El                      \" Ends the list
.\" .Sh ENVIRONMENT      \" May not be needed
.\" .Bl -tag -width "ENV_VAR_1" -indent \" ENV_VAR_1 is width of the string ENV_VAR_1
.\" .It Ev ENV_VAR_1
.\" Description of ENV_VAR_1
.\" .It Ev ENV_VAR_2
.\" Description of ENV_VAR_2
.\" .El                      
.\" .Sh FILES                \" File used or created by the topic of the man page
.\" .Bl -tag -width "/Users/joeuser/Library/really_long_file_name" -compact
.\" .It Pa /usr/share/file_name
.\" FILE_1 description
.\" .It Pa /Users/joeuser/Library/really_long_file_name
.\" FILE_2 description
.\" .El                      \" Ends the list
.\" .Sh DIAGNOSTICS       \" May not be needed
.\" .Bl -diag
.\" .It Diagnostic Tag
.\" Diagnostic informtion here.
.\" .It Diagnostic Tag
.\" Diagnostic informtion here.
.\" .El
.\" .Sh SEE ALSO 
.\" List links in ascending order by section, alphabetically within a section.
.\" Please do not reference files that do not exist without filing a bug report
.\" .Xr a 1 , 
.\" .Xr b 1 ,
.\" .Xr c 1 ,
.\" .Xr a 2 ,
.\" .Xr b 2 ,
.\" .Xr a 3 ,
.\" .Xr b 3 
.\" .Sh BUGS              \" Document known, unremedied bugs 
.\" .Sh HISTORY           \" Document history if command behaves in a unique manner
.Sh ABOUT
Get the source for
.Nm
at
.Ar https://bitbucket.org/thisismess/flynn
.Pp
Copyright 2013 Mess, All rights reserved.
